typedef struct Operand {
    char name[4];
    int immediate;
    int bytes;
} Operand;

typedef struct Opcode_Flags {
    char z;
    char n;
    char h;
    char c;
} Opcode_Flags;

typedef struct Opcode {
    int code;
    char mnemonic[16];
    int bytes;
    int total_cycles;
    int cycles[2];
    int num_operands;
    Operand operands[2];
    int immediate;
    Opcode_Flags flag;
} Opcode;

typedef struct Reverse_Record {
    int length;
    Keyword words[4];
    int code;
    int prefixed;
} Reverse_Record;

Opcode unprefixed[256] = {
    {0x00, "nop", 1, 4, {4, 0}, 0, {{"", false, 0}, {"", false, 0}}, true, {'-', '-', '-', '-'}},
    {0x01, "ld", 3, 12, {12, 0}, 2, {{"bc", true, 0}, {"d16", true, 2}}, true, {'-', '-', '-', '-'}},
    {0x02, "ld", 1, 8, {8, 0}, 2, {{"bc", false, 0}, {"a", true, 0}}, false, {'-', '-', '-', '-'}},
    {0x03, "inc", 1, 8, {8, 0}, 1, {{"bc", true, 0}, {"", false, 0}}, true, {'-', '-', '-', '-'}},
    {0x04, "inc", 1, 4, {4, 0}, 1, {{"b", true, 0}, {"", false, 0}}, true, {'z', '0', 'h', '-'}},
    {0x05, "dec", 1, 4, {4, 0}, 1, {{"b", true, 0}, {"", false, 0}}, true, {'z', '1', 'h', '-'}},
    {0x06, "ld", 2, 8, {8, 0}, 2, {{"b", true, 0}, {"d8", true, 1}}, true, {'-', '-', '-', '-'}},
    {0x07, "rlca", 1, 4, {4, 0}, 0, {{"", false, 0}, {"", false, 0}}, true, {'0', '0', '0', 'c'}},
    {0x08, "ld", 3, 20, {20, 0}, 2, {{"a16", false, 2}, {"sp", true, 0}}, false, {'-', '-', '-', '-'}},
    {0x09, "add", 1, 8, {8, 0}, 2, {{"hl", true, 0}, {"bc", true, 0}}, true, {'-', '0', 'h', 'c'}},
    {0x0a, "ld", 1, 8, {8, 0}, 2, {{"a", true, 0}, {"bc", false, 0}}, false, {'-', '-', '-', '-'}},
    {0x0b, "dec", 1, 8, {8, 0}, 1, {{"bc", true, 0}, {"", false, 0}}, true, {'-', '-', '-', '-'}},
    {0x0c, "inc", 1, 4, {4, 0}, 1, {{"c", true, 0}, {"", false, 0}}, true, {'z', '0', 'h', '-'}},
    {0x0d, "dec", 1, 4, {4, 0}, 1, {{"c", true, 0}, {"", false, 0}}, true, {'z', '1', 'h', '-'}},
    {0x0e, "ld", 2, 8, {8, 0}, 2, {{"c", true, 0}, {"d8", true, 1}}, true, {'-', '-', '-', '-'}},
    {0x0f, "rrca", 1, 4, {4, 0}, 0, {{"", false, 0}, {"", false, 0}}, true, {'0', '0', '0', 'c'}},
    {0x10, "stop", 2, 4, {4, 0}, 1, {{"d8", true, 1}, {"", false, 0}}, true, {'-', '-', '-', '-'}},
    {0x11, "ld", 3, 12, {12, 0}, 2, {{"de", true, 0}, {"d16", true, 2}}, true, {'-', '-', '-', '-'}},
    {0x12, "ld", 1, 8, {8, 0}, 2, {{"de", false, 0}, {"a", true, 0}}, false, {'-', '-', '-', '-'}},
    {0x13, "inc", 1, 8, {8, 0}, 1, {{"de", true, 0}, {"", false, 0}}, true, {'-', '-', '-', '-'}},
    {0x14, "inc", 1, 4, {4, 0}, 1, {{"d", true, 0}, {"", false, 0}}, true, {'z', '0', 'h', '-'}},
    {0x15, "dec", 1, 4, {4, 0}, 1, {{"d", true, 0}, {"", false, 0}}, true, {'z', '1', 'h', '-'}},
    {0x16, "ld", 2, 8, {8, 0}, 2, {{"d", true, 0}, {"d8", true, 1}}, true, {'-', '-', '-', '-'}},
    {0x17, "rla", 1, 4, {4, 0}, 0, {{"", false, 0}, {"", false, 0}}, true, {'0', '0', '0', 'c'}},
    {0x18, "jr", 2, 12, {12, 0}, 1, {{"r8", true, 1}, {"", false, 0}}, true, {'-', '-', '-', '-'}},
    {0x19, "add", 1, 8, {8, 0}, 2, {{"hl", true, 0}, {"de", true, 0}}, true, {'-', '0', 'h', 'c'}},
    {0x1a, "ld", 1, 8, {8, 0}, 2, {{"a", true, 0}, {"de", false, 0}}, false, {'-', '-', '-', '-'}},
    {0x1b, "dec", 1, 8, {8, 0}, 1, {{"de", true, 0}, {"", false, 0}}, true, {'-', '-', '-', '-'}},
    {0x1c, "inc", 1, 4, {4, 0}, 1, {{"e", true, 0}, {"", false, 0}}, true, {'z', '0', 'h', '-'}},
    {0x1d, "dec", 1, 4, {4, 0}, 1, {{"e", true, 0}, {"", false, 0}}, true, {'z', '1', 'h', '-'}},
    {0x1e, "ld", 2, 8, {8, 0}, 2, {{"e", true, 0}, {"d8", true, 1}}, true, {'-', '-', '-', '-'}},
    {0x1f, "rra", 1, 4, {4, 0}, 0, {{"", false, 0}, {"", false, 0}}, true, {'0', '0', '0', 'c'}},
    {0x20, "jr", 2, 20, {12, 8}, 2, {{"nz", true, 0}, {"r8", true, 1}}, true, {'-', '-', '-', '-'}},
    {0x21, "ld", 3, 12, {12, 0}, 2, {{"hl", true, 0}, {"d16", true, 2}}, true, {'-', '-', '-', '-'}},
    {0x22, "ld", 1, 8, {8, 0}, 2, {{"hl", false, 0}, {"a", true, 0}}, false, {'-', '-', '-', '-'}},
    {0x23, "inc", 1, 8, {8, 0}, 1, {{"hl", true, 0}, {"", false, 0}}, true, {'-', '-', '-', '-'}},
    {0x24, "inc", 1, 4, {4, 0}, 1, {{"h", true, 0}, {"", false, 0}}, true, {'z', '0', 'h', '-'}},
    {0x25, "dec", 1, 4, {4, 0}, 1, {{"h", true, 0}, {"", false, 0}}, true, {'z', '1', 'h', '-'}},
    {0x26, "ld", 2, 8, {8, 0}, 2, {{"h", true, 0}, {"d8", true, 1}}, true, {'-', '-', '-', '-'}},
    {0x27, "daa", 1, 4, {4, 0}, 0, {{"", false, 0}, {"", false, 0}}, true, {'z', '-', '0', 'c'}},
    {0x28, "jr", 2, 20, {12, 8}, 2, {{"z", true, 0}, {"r8", true, 1}}, true, {'-', '-', '-', '-'}},
    {0x29, "add", 1, 8, {8, 0}, 2, {{"hl", true, 0}, {"hl", true, 0}}, true, {'-', '0', 'h', 'c'}},
    {0x2a, "ld", 1, 8, {8, 0}, 2, {{"a", true, 0}, {"hl", false, 0}}, false, {'-', '-', '-', '-'}},
    {0x2b, "dec", 1, 8, {8, 0}, 1, {{"hl", true, 0}, {"", false, 0}}, true, {'-', '-', '-', '-'}},
    {0x2c, "inc", 1, 4, {4, 0}, 1, {{"l", true, 0}, {"", false, 0}}, true, {'z', '0', 'h', '-'}},
    {0x2d, "dec", 1, 4, {4, 0}, 1, {{"l", true, 0}, {"", false, 0}}, true, {'z', '1', 'h', '-'}},
    {0x2e, "ld", 2, 8, {8, 0}, 2, {{"l", true, 0}, {"d8", true, 1}}, true, {'-', '-', '-', '-'}},
    {0x2f, "cpl", 1, 4, {4, 0}, 0, {{"", false, 0}, {"", false, 0}}, true, {'-', '1', '1', '-'}},
    {0x30, "jr", 2, 20, {12, 8}, 2, {{"nc", true, 0}, {"r8", true, 1}}, true, {'-', '-', '-', '-'}},
    {0x31, "ld", 3, 12, {12, 0}, 2, {{"sp", true, 0}, {"d16", true, 2}}, true, {'-', '-', '-', '-'}},
    {0x32, "ld", 1, 8, {8, 0}, 2, {{"hl", false, 0}, {"a", true, 0}}, false, {'-', '-', '-', '-'}},
    {0x33, "inc", 1, 8, {8, 0}, 1, {{"sp", true, 0}, {"", false, 0}}, true, {'-', '-', '-', '-'}},
    {0x34, "inc", 1, 12, {12, 0}, 1, {{"hl", false, 0}, {"", false, 0}}, false, {'z', '0', 'h', '-'}},
    {0x35, "dec", 1, 12, {12, 0}, 1, {{"hl", false, 0}, {"", false, 0}}, false, {'z', '1', 'h', '-'}},
    {0x36, "ld", 2, 12, {12, 0}, 2, {{"hl", false, 0}, {"d8", true, 1}}, false, {'-', '-', '-', '-'}},
    {0x37, "scf", 1, 4, {4, 0}, 0, {{"", false, 0}, {"", false, 0}}, true, {'-', '0', '0', '1'}},
    {0x38, "jr", 2, 20, {12, 8}, 2, {{"c", true, 0}, {"r8", true, 1}}, true, {'-', '-', '-', '-'}},
    {0x39, "add", 1, 8, {8, 0}, 2, {{"hl", true, 0}, {"sp", true, 0}}, true, {'-', '0', 'h', 'c'}},
    {0x3a, "ld", 1, 8, {8, 0}, 2, {{"a", true, 0}, {"hl", false, 0}}, false, {'-', '-', '-', '-'}},
    {0x3b, "dec", 1, 8, {8, 0}, 1, {{"sp", true, 0}, {"", false, 0}}, true, {'-', '-', '-', '-'}},
    {0x3c, "inc", 1, 4, {4, 0}, 1, {{"a", true, 0}, {"", false, 0}}, true, {'z', '0', 'h', '-'}},
    {0x3d, "dec", 1, 4, {4, 0}, 1, {{"a", true, 0}, {"", false, 0}}, true, {'z', '1', 'h', '-'}},
    {0x3e, "ld", 2, 8, {8, 0}, 2, {{"a", true, 0}, {"d8", true, 1}}, true, {'-', '-', '-', '-'}},
    {0x3f, "ccf", 1, 4, {4, 0}, 0, {{"", false, 0}, {"", false, 0}}, true, {'-', '0', '0', 'c'}},
    {0x40, "ld", 1, 4, {4, 0}, 2, {{"b", true, 0}, {"b", true, 0}}, true, {'-', '-', '-', '-'}},
    {0x41, "ld", 1, 4, {4, 0}, 2, {{"b", true, 0}, {"c", true, 0}}, true, {'-', '-', '-', '-'}},
    {0x42, "ld", 1, 4, {4, 0}, 2, {{"b", true, 0}, {"d", true, 0}}, true, {'-', '-', '-', '-'}},
    {0x43, "ld", 1, 4, {4, 0}, 2, {{"b", true, 0}, {"e", true, 0}}, true, {'-', '-', '-', '-'}},
    {0x44, "ld", 1, 4, {4, 0}, 2, {{"b", true, 0}, {"h", true, 0}}, true, {'-', '-', '-', '-'}},
    {0x45, "ld", 1, 4, {4, 0}, 2, {{"b", true, 0}, {"l", true, 0}}, true, {'-', '-', '-', '-'}},
    {0x46, "ld", 1, 8, {8, 0}, 2, {{"b", true, 0}, {"hl", false, 0}}, false, {'-', '-', '-', '-'}},
    {0x47, "ld", 1, 4, {4, 0}, 2, {{"b", true, 0}, {"a", true, 0}}, true, {'-', '-', '-', '-'}},
    {0x48, "ld", 1, 4, {4, 0}, 2, {{"c", true, 0}, {"b", true, 0}}, true, {'-', '-', '-', '-'}},
    {0x49, "ld", 1, 4, {4, 0}, 2, {{"c", true, 0}, {"c", true, 0}}, true, {'-', '-', '-', '-'}},
    {0x4a, "ld", 1, 4, {4, 0}, 2, {{"c", true, 0}, {"d", true, 0}}, true, {'-', '-', '-', '-'}},
    {0x4b, "ld", 1, 4, {4, 0}, 2, {{"c", true, 0}, {"e", true, 0}}, true, {'-', '-', '-', '-'}},
    {0x4c, "ld", 1, 4, {4, 0}, 2, {{"c", true, 0}, {"h", true, 0}}, true, {'-', '-', '-', '-'}},
    {0x4d, "ld", 1, 4, {4, 0}, 2, {{"c", true, 0}, {"l", true, 0}}, true, {'-', '-', '-', '-'}},
    {0x4e, "ld", 1, 8, {8, 0}, 2, {{"c", true, 0}, {"hl", false, 0}}, false, {'-', '-', '-', '-'}},
    {0x4f, "ld", 1, 4, {4, 0}, 2, {{"c", true, 0}, {"a", true, 0}}, true, {'-', '-', '-', '-'}},
    {0x50, "ld", 1, 4, {4, 0}, 2, {{"d", true, 0}, {"b", true, 0}}, true, {'-', '-', '-', '-'}},
    {0x51, "ld", 1, 4, {4, 0}, 2, {{"d", true, 0}, {"c", true, 0}}, true, {'-', '-', '-', '-'}},
    {0x52, "ld", 1, 4, {4, 0}, 2, {{"d", true, 0}, {"d", true, 0}}, true, {'-', '-', '-', '-'}},
    {0x53, "ld", 1, 4, {4, 0}, 2, {{"d", true, 0}, {"e", true, 0}}, true, {'-', '-', '-', '-'}},
    {0x54, "ld", 1, 4, {4, 0}, 2, {{"d", true, 0}, {"h", true, 0}}, true, {'-', '-', '-', '-'}},
    {0x55, "ld", 1, 4, {4, 0}, 2, {{"d", true, 0}, {"l", true, 0}}, true, {'-', '-', '-', '-'}},
    {0x56, "ld", 1, 8, {8, 0}, 2, {{"d", true, 0}, {"hl", false, 0}}, false, {'-', '-', '-', '-'}},
    {0x57, "ld", 1, 4, {4, 0}, 2, {{"d", true, 0}, {"a", true, 0}}, true, {'-', '-', '-', '-'}},
    {0x58, "ld", 1, 4, {4, 0}, 2, {{"e", true, 0}, {"b", true, 0}}, true, {'-', '-', '-', '-'}},
    {0x59, "ld", 1, 4, {4, 0}, 2, {{"e", true, 0}, {"c", true, 0}}, true, {'-', '-', '-', '-'}},
    {0x5a, "ld", 1, 4, {4, 0}, 2, {{"e", true, 0}, {"d", true, 0}}, true, {'-', '-', '-', '-'}},
    {0x5b, "ld", 1, 4, {4, 0}, 2, {{"e", true, 0}, {"e", true, 0}}, true, {'-', '-', '-', '-'}},
    {0x5c, "ld", 1, 4, {4, 0}, 2, {{"e", true, 0}, {"h", true, 0}}, true, {'-', '-', '-', '-'}},
    {0x5d, "ld", 1, 4, {4, 0}, 2, {{"e", true, 0}, {"l", true, 0}}, true, {'-', '-', '-', '-'}},
    {0x5e, "ld", 1, 8, {8, 0}, 2, {{"e", true, 0}, {"hl", false, 0}}, false, {'-', '-', '-', '-'}},
    {0x5f, "ld", 1, 4, {4, 0}, 2, {{"e", true, 0}, {"a", true, 0}}, true, {'-', '-', '-', '-'}},
    {0x60, "ld", 1, 4, {4, 0}, 2, {{"h", true, 0}, {"b", true, 0}}, true, {'-', '-', '-', '-'}},
    {0x61, "ld", 1, 4, {4, 0}, 2, {{"h", true, 0}, {"c", true, 0}}, true, {'-', '-', '-', '-'}},
    {0x62, "ld", 1, 4, {4, 0}, 2, {{"h", true, 0}, {"d", true, 0}}, true, {'-', '-', '-', '-'}},
    {0x63, "ld", 1, 4, {4, 0}, 2, {{"h", true, 0}, {"e", true, 0}}, true, {'-', '-', '-', '-'}},
    {0x64, "ld", 1, 4, {4, 0}, 2, {{"h", true, 0}, {"h", true, 0}}, true, {'-', '-', '-', '-'}},
    {0x65, "ld", 1, 4, {4, 0}, 2, {{"h", true, 0}, {"l", true, 0}}, true, {'-', '-', '-', '-'}},
    {0x66, "ld", 1, 8, {8, 0}, 2, {{"h", true, 0}, {"hl", false, 0}}, false, {'-', '-', '-', '-'}},
    {0x67, "ld", 1, 4, {4, 0}, 2, {{"h", true, 0}, {"a", true, 0}}, true, {'-', '-', '-', '-'}},
    {0x68, "ld", 1, 4, {4, 0}, 2, {{"l", true, 0}, {"b", true, 0}}, true, {'-', '-', '-', '-'}},
    {0x69, "ld", 1, 4, {4, 0}, 2, {{"l", true, 0}, {"c", true, 0}}, true, {'-', '-', '-', '-'}},
    {0x6a, "ld", 1, 4, {4, 0}, 2, {{"l", true, 0}, {"d", true, 0}}, true, {'-', '-', '-', '-'}},
    {0x6b, "ld", 1, 4, {4, 0}, 2, {{"l", true, 0}, {"e", true, 0}}, true, {'-', '-', '-', '-'}},
    {0x6c, "ld", 1, 4, {4, 0}, 2, {{"l", true, 0}, {"h", true, 0}}, true, {'-', '-', '-', '-'}},
    {0x6d, "ld", 1, 4, {4, 0}, 2, {{"l", true, 0}, {"l", true, 0}}, true, {'-', '-', '-', '-'}},
    {0x6e, "ld", 1, 8, {8, 0}, 2, {{"l", true, 0}, {"hl", false, 0}}, false, {'-', '-', '-', '-'}},
    {0x6f, "ld", 1, 4, {4, 0}, 2, {{"l", true, 0}, {"a", true, 0}}, true, {'-', '-', '-', '-'}},
    {0x70, "ld", 1, 8, {8, 0}, 2, {{"hl", false, 0}, {"b", true, 0}}, false, {'-', '-', '-', '-'}},
    {0x71, "ld", 1, 8, {8, 0}, 2, {{"hl", false, 0}, {"c", true, 0}}, false, {'-', '-', '-', '-'}},
    {0x72, "ld", 1, 8, {8, 0}, 2, {{"hl", false, 0}, {"d", true, 0}}, false, {'-', '-', '-', '-'}},
    {0x73, "ld", 1, 8, {8, 0}, 2, {{"hl", false, 0}, {"e", true, 0}}, false, {'-', '-', '-', '-'}},
    {0x74, "ld", 1, 8, {8, 0}, 2, {{"hl", false, 0}, {"h", true, 0}}, false, {'-', '-', '-', '-'}},
    {0x75, "ld", 1, 8, {8, 0}, 2, {{"hl", false, 0}, {"l", true, 0}}, false, {'-', '-', '-', '-'}},
    {0x76, "halt", 1, 4, {4, 0}, 0, {{"", false, 0}, {"", false, 0}}, true, {'-', '-', '-', '-'}},
    {0x77, "ld", 1, 8, {8, 0}, 2, {{"hl", false, 0}, {"a", true, 0}}, false, {'-', '-', '-', '-'}},
    {0x78, "ld", 1, 4, {4, 0}, 2, {{"a", true, 0}, {"b", true, 0}}, true, {'-', '-', '-', '-'}},
    {0x79, "ld", 1, 4, {4, 0}, 2, {{"a", true, 0}, {"c", true, 0}}, true, {'-', '-', '-', '-'}},
    {0x7a, "ld", 1, 4, {4, 0}, 2, {{"a", true, 0}, {"d", true, 0}}, true, {'-', '-', '-', '-'}},
    {0x7b, "ld", 1, 4, {4, 0}, 2, {{"a", true, 0}, {"e", true, 0}}, true, {'-', '-', '-', '-'}},
    {0x7c, "ld", 1, 4, {4, 0}, 2, {{"a", true, 0}, {"h", true, 0}}, true, {'-', '-', '-', '-'}},
    {0x7d, "ld", 1, 4, {4, 0}, 2, {{"a", true, 0}, {"l", true, 0}}, true, {'-', '-', '-', '-'}},
    {0x7e, "ld", 1, 8, {8, 0}, 2, {{"a", true, 0}, {"hl", false, 0}}, false, {'-', '-', '-', '-'}},
    {0x7f, "ld", 1, 4, {4, 0}, 2, {{"a", true, 0}, {"a", true, 0}}, true, {'-', '-', '-', '-'}},
    {0x80, "add", 1, 4, {4, 0}, 2, {{"a", true, 0}, {"b", true, 0}}, true, {'z', '0', 'h', 'c'}},
    {0x81, "add", 1, 4, {4, 0}, 2, {{"a", true, 0}, {"c", true, 0}}, true, {'z', '0', 'h', 'c'}},
    {0x82, "add", 1, 4, {4, 0}, 2, {{"a", true, 0}, {"d", true, 0}}, true, {'z', '0', 'h', 'c'}},
    {0x83, "add", 1, 4, {4, 0}, 2, {{"a", true, 0}, {"e", true, 0}}, true, {'z', '0', 'h', 'c'}},
    {0x84, "add", 1, 4, {4, 0}, 2, {{"a", true, 0}, {"h", true, 0}}, true, {'z', '0', 'h', 'c'}},
    {0x85, "add", 1, 4, {4, 0}, 2, {{"a", true, 0}, {"l", true, 0}}, true, {'z', '0', 'h', 'c'}},
    {0x86, "add", 1, 8, {8, 0}, 2, {{"a", true, 0}, {"hl", false, 0}}, false, {'z', '0', 'h', 'c'}},
    {0x87, "add", 1, 4, {4, 0}, 2, {{"a", true, 0}, {"a", true, 0}}, true, {'z', '0', 'h', 'c'}},
    {0x88, "adc", 1, 4, {4, 0}, 2, {{"a", true, 0}, {"b", true, 0}}, true, {'z', '0', 'h', 'c'}},
    {0x89, "adc", 1, 4, {4, 0}, 2, {{"a", true, 0}, {"c", true, 0}}, true, {'z', '0', 'h', 'c'}},
    {0x8a, "adc", 1, 4, {4, 0}, 2, {{"a", true, 0}, {"d", true, 0}}, true, {'z', '0', 'h', 'c'}},
    {0x8b, "adc", 1, 4, {4, 0}, 2, {{"a", true, 0}, {"e", true, 0}}, true, {'z', '0', 'h', 'c'}},
    {0x8c, "adc", 1, 4, {4, 0}, 2, {{"a", true, 0}, {"h", true, 0}}, true, {'z', '0', 'h', 'c'}},
    {0x8d, "adc", 1, 4, {4, 0}, 2, {{"a", true, 0}, {"l", true, 0}}, true, {'z', '0', 'h', 'c'}},
    {0x8e, "adc", 1, 8, {8, 0}, 2, {{"a", true, 0}, {"hl", false, 0}}, false, {'z', '0', 'h', 'c'}},
    {0x8f, "adc", 1, 4, {4, 0}, 2, {{"a", true, 0}, {"a", true, 0}}, true, {'z', '0', 'h', 'c'}},
    {0x90, "sub", 1, 4, {4, 0}, 1, {{"b", true, 0}, {"", false, 0}}, true, {'z', '1', 'h', 'c'}},
    {0x91, "sub", 1, 4, {4, 0}, 1, {{"c", true, 0}, {"", false, 0}}, true, {'z', '1', 'h', 'c'}},
    {0x92, "sub", 1, 4, {4, 0}, 1, {{"d", true, 0}, {"", false, 0}}, true, {'z', '1', 'h', 'c'}},
    {0x93, "sub", 1, 4, {4, 0}, 1, {{"e", true, 0}, {"", false, 0}}, true, {'z', '1', 'h', 'c'}},
    {0x94, "sub", 1, 4, {4, 0}, 1, {{"h", true, 0}, {"", false, 0}}, true, {'z', '1', 'h', 'c'}},
    {0x95, "sub", 1, 4, {4, 0}, 1, {{"l", true, 0}, {"", false, 0}}, true, {'z', '1', 'h', 'c'}},
    {0x96, "sub", 1, 8, {8, 0}, 1, {{"hl", false, 0}, {"", false, 0}}, false, {'z', '1', 'h', 'c'}},
    {0x97, "sub", 1, 4, {4, 0}, 1, {{"a", true, 0}, {"", false, 0}}, true, {'1', '1', '0', '0'}},
    {0x98, "sbc", 1, 4, {4, 0}, 2, {{"a", true, 0}, {"b", true, 0}}, true, {'z', '1', 'h', 'c'}},
    {0x99, "sbc", 1, 4, {4, 0}, 2, {{"a", true, 0}, {"c", true, 0}}, true, {'z', '1', 'h', 'c'}},
    {0x9a, "sbc", 1, 4, {4, 0}, 2, {{"a", true, 0}, {"d", true, 0}}, true, {'z', '1', 'h', 'c'}},
    {0x9b, "sbc", 1, 4, {4, 0}, 2, {{"a", true, 0}, {"e", true, 0}}, true, {'z', '1', 'h', 'c'}},
    {0x9c, "sbc", 1, 4, {4, 0}, 2, {{"a", true, 0}, {"h", true, 0}}, true, {'z', '1', 'h', 'c'}},
    {0x9d, "sbc", 1, 4, {4, 0}, 2, {{"a", true, 0}, {"l", true, 0}}, true, {'z', '1', 'h', 'c'}},
    {0x9e, "sbc", 1, 8, {8, 0}, 2, {{"a", true, 0}, {"hl", false, 0}}, false, {'z', '1', 'h', 'c'}},
    {0x9f, "sbc", 1, 4, {4, 0}, 2, {{"a", true, 0}, {"a", true, 0}}, true, {'z', '1', 'h', 'c'}},
    {0xa0, "and", 1, 4, {4, 0}, 1, {{"b", true, 0}, {"", false, 0}}, true, {'z', '0', '1', '0'}},
    {0xa1, "and", 1, 4, {4, 0}, 1, {{"c", true, 0}, {"", false, 0}}, true, {'z', '0', '1', '0'}},
    {0xa2, "and", 1, 4, {4, 0}, 1, {{"d", true, 0}, {"", false, 0}}, true, {'z', '0', '1', '0'}},
    {0xa3, "and", 1, 4, {4, 0}, 1, {{"e", true, 0}, {"", false, 0}}, true, {'z', '0', '1', '0'}},
    {0xa4, "and", 1, 4, {4, 0}, 1, {{"h", true, 0}, {"", false, 0}}, true, {'z', '0', '1', '0'}},
    {0xa5, "and", 1, 4, {4, 0}, 1, {{"l", true, 0}, {"", false, 0}}, true, {'z', '0', '1', '0'}},
    {0xa6, "and", 1, 8, {8, 0}, 1, {{"hl", false, 0}, {"", false, 0}}, false, {'z', '0', '1', '0'}},
    {0xa7, "and", 1, 4, {4, 0}, 1, {{"a", true, 0}, {"", false, 0}}, true, {'z', '0', '1', '0'}},
    {0xa8, "xor", 1, 4, {4, 0}, 1, {{"b", true, 0}, {"", false, 0}}, true, {'z', '0', '0', '0'}},
    {0xa9, "xor", 1, 4, {4, 0}, 1, {{"c", true, 0}, {"", false, 0}}, true, {'z', '0', '0', '0'}},
    {0xaa, "xor", 1, 4, {4, 0}, 1, {{"d", true, 0}, {"", false, 0}}, true, {'z', '0', '0', '0'}},
    {0xab, "xor", 1, 4, {4, 0}, 1, {{"e", true, 0}, {"", false, 0}}, true, {'z', '0', '0', '0'}},
    {0xac, "xor", 1, 4, {4, 0}, 1, {{"h", true, 0}, {"", false, 0}}, true, {'z', '0', '0', '0'}},
    {0xad, "xor", 1, 4, {4, 0}, 1, {{"l", true, 0}, {"", false, 0}}, true, {'z', '0', '0', '0'}},
    {0xae, "xor", 1, 8, {8, 0}, 1, {{"hl", false, 0}, {"", false, 0}}, false, {'z', '0', '0', '0'}},
    {0xaf, "xor", 1, 4, {4, 0}, 1, {{"a", true, 0}, {"", false, 0}}, true, {'1', '0', '0', '0'}},
    {0xb0, "or", 1, 4, {4, 0}, 1, {{"b", true, 0}, {"", false, 0}}, true, {'z', '0', '0', '0'}},
    {0xb1, "or", 1, 4, {4, 0}, 1, {{"c", true, 0}, {"", false, 0}}, true, {'z', '0', '0', '0'}},
    {0xb2, "or", 1, 4, {4, 0}, 1, {{"d", true, 0}, {"", false, 0}}, true, {'z', '0', '0', '0'}},
    {0xb3, "or", 1, 4, {4, 0}, 1, {{"e", true, 0}, {"", false, 0}}, true, {'z', '0', '0', '0'}},
    {0xb4, "or", 1, 4, {4, 0}, 1, {{"h", true, 0}, {"", false, 0}}, true, {'z', '0', '0', '0'}},
    {0xb5, "or", 1, 4, {4, 0}, 1, {{"l", true, 0}, {"", false, 0}}, true, {'z', '0', '0', '0'}},
    {0xb6, "or", 1, 8, {8, 0}, 1, {{"hl", false, 0}, {"", false, 0}}, false, {'z', '0', '0', '0'}},
    {0xb7, "or", 1, 4, {4, 0}, 1, {{"a", true, 0}, {"", false, 0}}, true, {'z', '0', '0', '0'}},
    {0xb8, "cp", 1, 4, {4, 0}, 1, {{"b", true, 0}, {"", false, 0}}, true, {'z', '1', 'h', 'c'}},
    {0xb9, "cp", 1, 4, {4, 0}, 1, {{"c", true, 0}, {"", false, 0}}, true, {'z', '1', 'h', 'c'}},
    {0xba, "cp", 1, 4, {4, 0}, 1, {{"d", true, 0}, {"", false, 0}}, true, {'z', '1', 'h', 'c'}},
    {0xbb, "cp", 1, 4, {4, 0}, 1, {{"e", true, 0}, {"", false, 0}}, true, {'z', '1', 'h', 'c'}},
    {0xbc, "cp", 1, 4, {4, 0}, 1, {{"h", true, 0}, {"", false, 0}}, true, {'z', '1', 'h', 'c'}},
    {0xbd, "cp", 1, 4, {4, 0}, 1, {{"l", true, 0}, {"", false, 0}}, true, {'z', '1', 'h', 'c'}},
    {0xbe, "cp", 1, 8, {8, 0}, 1, {{"hl", false, 0}, {"", false, 0}}, false, {'z', '1', 'h', 'c'}},
    {0xbf, "cp", 1, 4, {4, 0}, 1, {{"a", true, 0}, {"", false, 0}}, true, {'1', '1', '0', '0'}},
    {0xc0, "ret", 1, 28, {20, 8}, 1, {{"nz", true, 0}, {"", false, 0}}, true, {'-', '-', '-', '-'}},
    {0xc1, "pop", 1, 12, {12, 0}, 1, {{"bc", true, 0}, {"", false, 0}}, true, {'-', '-', '-', '-'}},
    {0xc2, "jp", 3, 28, {16, 12}, 2, {{"nz", true, 0}, {"a16", true, 2}}, true, {'-', '-', '-', '-'}},
    {0xc3, "jp", 3, 16, {16, 0}, 1, {{"a16", true, 2}, {"", false, 0}}, true, {'-', '-', '-', '-'}},
    {0xc4, "call", 3, 36, {24, 12}, 2, {{"nz", true, 0}, {"a16", true, 2}}, true, {'-', '-', '-', '-'}},
    {0xc5, "push", 1, 16, {16, 0}, 1, {{"bc", true, 0}, {"", false, 0}}, true, {'-', '-', '-', '-'}},
    {0xc6, "add", 2, 8, {8, 0}, 2, {{"a", true, 0}, {"d8", true, 1}}, true, {'z', '0', 'h', 'c'}},
    {0xc7, "rst", 1, 16, {16, 0}, 1, {{"00h", true, 0}, {"", false, 0}}, true, {'-', '-', '-', '-'}},
    {0xc8, "ret", 1, 28, {20, 8}, 1, {{"z", true, 0}, {"", false, 0}}, true, {'-', '-', '-', '-'}},
    {0xc9, "ret", 1, 16, {16, 0}, 0, {{"", false, 0}, {"", false, 0}}, true, {'-', '-', '-', '-'}},
    {0xca, "jp", 3, 28, {16, 12}, 2, {{"z", true, 0}, {"a16", true, 2}}, true, {'-', '-', '-', '-'}},
    {0xcb, "prefix", 1, 4, {4, 0}, 0, {{"", false, 0}, {"", false, 0}}, true, {'-', '-', '-', '-'}},
    {0xcc, "call", 3, 36, {24, 12}, 2, {{"z", true, 0}, {"a16", true, 2}}, true, {'-', '-', '-', '-'}},
    {0xcd, "call", 3, 24, {24, 0}, 1, {{"a16", true, 2}, {"", false, 0}}, true, {'-', '-', '-', '-'}},
    {0xce, "adc", 2, 8, {8, 0}, 2, {{"a", true, 0}, {"d8", true, 1}}, true, {'z', '0', 'h', 'c'}},
    {0xcf, "rst", 1, 16, {16, 0}, 1, {{"08h", true, 0}, {"", false, 0}}, true, {'-', '-', '-', '-'}},
    {0xd0, "ret", 1, 28, {20, 8}, 1, {{"nc", true, 0}, {"", false, 0}}, true, {'-', '-', '-', '-'}},
    {0xd1, "pop", 1, 12, {12, 0}, 1, {{"de", true, 0}, {"", false, 0}}, true, {'-', '-', '-', '-'}},
    {0xd2, "jp", 3, 28, {16, 12}, 2, {{"nc", true, 0}, {"a16", true, 2}}, true, {'-', '-', '-', '-'}},
    {0xd3, "illegal_d3", 1, 4, {4, 0}, 0, {{"", false, 0}, {"", false, 0}}, true, {'-', '-', '-', '-'}},
    {0xd4, "call", 3, 36, {24, 12}, 2, {{"nc", true, 0}, {"a16", true, 2}}, true, {'-', '-', '-', '-'}},
    {0xd5, "push", 1, 16, {16, 0}, 1, {{"de", true, 0}, {"", false, 0}}, true, {'-', '-', '-', '-'}},
    {0xd6, "sub", 2, 8, {8, 0}, 1, {{"d8", true, 1}, {"", false, 0}}, true, {'z', '1', 'h', 'c'}},
    {0xd7, "rst", 1, 16, {16, 0}, 1, {{"10h", true, 0}, {"", false, 0}}, true, {'-', '-', '-', '-'}},
    {0xd8, "ret", 1, 28, {20, 8}, 1, {{"c", true, 0}, {"", false, 0}}, true, {'-', '-', '-', '-'}},
    {0xd9, "reti", 1, 16, {16, 0}, 0, {{"", false, 0}, {"", false, 0}}, true, {'-', '-', '-', '-'}},
    {0xda, "jp", 3, 28, {16, 12}, 2, {{"c", true, 0}, {"a16", true, 2}}, true, {'-', '-', '-', '-'}},
    {0xdb, "illegal_db", 1, 4, {4, 0}, 0, {{"", false, 0}, {"", false, 0}}, true, {'-', '-', '-', '-'}},
    {0xdc, "call", 3, 36, {24, 12}, 2, {{"c", true, 0}, {"a16", true, 2}}, true, {'-', '-', '-', '-'}},
    {0xdd, "illegal_dd", 1, 4, {4, 0}, 0, {{"", false, 0}, {"", false, 0}}, true, {'-', '-', '-', '-'}},
    {0xde, "sbc", 2, 8, {8, 0}, 2, {{"a", true, 0}, {"d8", true, 1}}, true, {'z', '1', 'h', 'c'}},
    {0xdf, "rst", 1, 16, {16, 0}, 1, {{"18h", true, 0}, {"", false, 0}}, true, {'-', '-', '-', '-'}},
    {0xe0, "ldh", 2, 12, {12, 0}, 2, {{"a8", false, 1}, {"a", true, 0}}, false, {'-', '-', '-', '-'}},
    {0xe1, "pop", 1, 12, {12, 0}, 1, {{"hl", true, 0}, {"", false, 0}}, true, {'-', '-', '-', '-'}},
    {0xe2, "ld", 1, 8, {8, 0}, 2, {{"c", false, 0}, {"a", true, 0}}, false, {'-', '-', '-', '-'}},
    {0xe3, "illegal_e3", 1, 4, {4, 0}, 0, {{"", false, 0}, {"", false, 0}}, true, {'-', '-', '-', '-'}},
    {0xe4, "illegal_e4", 1, 4, {4, 0}, 0, {{"", false, 0}, {"", false, 0}}, true, {'-', '-', '-', '-'}},
    {0xe5, "push", 1, 16, {16, 0}, 1, {{"hl", true, 0}, {"", false, 0}}, true, {'-', '-', '-', '-'}},
    {0xe6, "and", 2, 8, {8, 0}, 1, {{"d8", true, 1}, {"", false, 0}}, true, {'z', '0', '1', '0'}},
    {0xe7, "rst", 1, 16, {16, 0}, 1, {{"20h", true, 0}, {"", false, 0}}, true, {'-', '-', '-', '-'}},
    {0xe8, "add", 2, 16, {16, 0}, 2, {{"sp", true, 0}, {"r8", true, 1}}, true, {'0', '0', 'h', 'c'}},
    {0xe9, "jp", 1, 4, {4, 0}, 1, {{"hl", true, 0}, {"", false, 0}}, true, {'-', '-', '-', '-'}},
    {0xea, "ld", 3, 16, {16, 0}, 2, {{"a16", false, 2}, {"a", true, 0}}, false, {'-', '-', '-', '-'}},
    {0xeb, "illegal_eb", 1, 4, {4, 0}, 0, {{"", false, 0}, {"", false, 0}}, true, {'-', '-', '-', '-'}},
    {0xec, "illegal_ec", 1, 4, {4, 0}, 0, {{"", false, 0}, {"", false, 0}}, true, {'-', '-', '-', '-'}},
    {0xed, "illegal_ed", 1, 4, {4, 0}, 0, {{"", false, 0}, {"", false, 0}}, true, {'-', '-', '-', '-'}},
    {0xee, "xor", 2, 8, {8, 0}, 1, {{"d8", true, 1}, {"", false, 0}}, true, {'z', '0', '0', '0'}},
    {0xef, "rst", 1, 16, {16, 0}, 1, {{"28h", true, 0}, {"", false, 0}}, true, {'-', '-', '-', '-'}},
    {0xf0, "ldh", 2, 12, {12, 0}, 2, {{"a", true, 0}, {"a8", false, 1}}, false, {'-', '-', '-', '-'}},
    {0xf1, "pop", 1, 12, {12, 0}, 1, {{"af", true, 0}, {"", false, 0}}, true, {'z', 'n', 'h', 'c'}},
    {0xf2, "ld", 1, 8, {8, 0}, 2, {{"a", true, 0}, {"c", false, 0}}, false, {'-', '-', '-', '-'}},
    {0xf3, "di", 1, 4, {4, 0}, 0, {{"", false, 0}, {"", false, 0}}, true, {'-', '-', '-', '-'}},
    {0xf4, "illegal_f4", 1, 4, {4, 0}, 0, {{"", false, 0}, {"", false, 0}}, true, {'-', '-', '-', '-'}},
    {0xf5, "push", 1, 16, {16, 0}, 1, {{"af", true, 0}, {"", false, 0}}, true, {'-', '-', '-', '-'}},
    {0xf6, "or", 2, 8, {8, 0}, 1, {{"d8", true, 1}, {"", false, 0}}, true, {'z', '0', '0', '0'}},
    {0xf7, "rst", 1, 16, {16, 0}, 1, {{"30h", true, 0}, {"", false, 0}}, true, {'-', '-', '-', '-'}},
    {0xf8, "ld", 2, 12, {12, 0}, 3, {{"hl", true, 0}, {"sp", true, 0}}, true, {'0', '0', 'h', 'c'}},
    {0xf9, "ld", 1, 8, {8, 0}, 2, {{"sp", true, 0}, {"hl", true, 0}}, true, {'-', '-', '-', '-'}},
    {0xfa, "ld", 3, 16, {16, 0}, 2, {{"a", true, 0}, {"a16", false, 2}}, false, {'-', '-', '-', '-'}},
    {0xfb, "ei", 1, 4, {4, 0}, 0, {{"", false, 0}, {"", false, 0}}, true, {'-', '-', '-', '-'}},
    {0xfc, "illegal_fc", 1, 4, {4, 0}, 0, {{"", false, 0}, {"", false, 0}}, true, {'-', '-', '-', '-'}},
    {0xfd, "illegal_fd", 1, 4, {4, 0}, 0, {{"", false, 0}, {"", false, 0}}, true, {'-', '-', '-', '-'}},
    {0xfe, "cp", 2, 8, {8, 0}, 1, {{"d8", true, 1}, {"", false, 0}}, true, {'z', '1', 'h', 'c'}},
    {0xff, "rst", 1, 16, {16, 0}, 1, {{"38h", true, 0}, {"", false, 0}}, true, {'-', '-', '-', '-'}}
};



Reverse_Record reversed[512] = {
    {1, {keyword_nop, keyword_nil, keyword_nil, keyword_nil}, 0x00, false},
    {3, {keyword_ld, keyword_bc, keyword_u16, keyword_nil}, 0x01, false},
    {3, {keyword_ld, keyword_bc, keyword_a, keyword_nil}, 0x02, false},
    {2, {keyword_inc, keyword_bc, keyword_nil, keyword_nil}, 0x03, false},
    {2, {keyword_inc, keyword_b, keyword_nil, keyword_nil}, 0x04, false},
    {2, {keyword_dec, keyword_b, keyword_nil, keyword_nil}, 0x05, false},
    {3, {keyword_ld, keyword_b, keyword_u8, keyword_nil}, 0x06, false},
    {1, {keyword_rlca, keyword_nil, keyword_nil, keyword_nil}, 0x07, false},
    {3, {keyword_ld, keyword_a16, keyword_sp, keyword_nil}, 0x08, false},
    {3, {keyword_add, keyword_hl, keyword_bc, keyword_nil}, 0x09, false},
    {3, {keyword_ld, keyword_a, keyword_bc, keyword_nil}, 0x0a, false},
    {2, {keyword_dec, keyword_bc, keyword_nil, keyword_nil}, 0x0b, false},
    {2, {keyword_inc, keyword_c, keyword_nil, keyword_nil}, 0x0c, false},
    {2, {keyword_dec, keyword_c, keyword_nil, keyword_nil}, 0x0d, false},
    {3, {keyword_ld, keyword_c, keyword_u8, keyword_nil}, 0x0e, false},
    {1, {keyword_rrca, keyword_nil, keyword_nil, keyword_nil}, 0x0f, false},
    {2, {keyword_stop, keyword_u8, keyword_nil, keyword_nil}, 0x10, false},
    {3, {keyword_ld, keyword_de, keyword_u16, keyword_nil}, 0x11, false},
    {3, {keyword_ld, keyword_de, keyword_a, keyword_nil}, 0x12, false},
    {2, {keyword_inc, keyword_de, keyword_nil, keyword_nil}, 0x13, false},
    {2, {keyword_inc, keyword_d, keyword_nil, keyword_nil}, 0x14, false},
    {2, {keyword_dec, keyword_d, keyword_nil, keyword_nil}, 0x15, false},
    {3, {keyword_ld, keyword_d, keyword_u8, keyword_nil}, 0x16, false},
    {1, {keyword_rla, keyword_nil, keyword_nil, keyword_nil}, 0x17, false},
    {2, {keyword_jr, keyword_r8, keyword_nil, keyword_nil}, 0x18, false},
    {3, {keyword_add, keyword_hl, keyword_de, keyword_nil}, 0x19, false},
    {3, {keyword_ld, keyword_a, keyword_de, keyword_nil}, 0x1a, false},
    {2, {keyword_dec, keyword_de, keyword_nil, keyword_nil}, 0x1b, false},
    {2, {keyword_inc, keyword_e, keyword_nil, keyword_nil}, 0x1c, false},
    {2, {keyword_dec, keyword_e, keyword_nil, keyword_nil}, 0x1d, false},
    {3, {keyword_ld, keyword_e, keyword_u8, keyword_nil}, 0x1e, false},
    {1, {keyword_rra, keyword_nil, keyword_nil, keyword_nil}, 0x1f, false},
    {3, {keyword_jr, keyword_flag_nz, keyword_r8, keyword_nil}, 0x20, false},
    {3, {keyword_ld, keyword_hl, keyword_u16, keyword_nil}, 0x21, false},
    {3, {keyword_ld, keyword_hl, keyword_a, keyword_nil}, 0x22, false},
    {2, {keyword_inc, keyword_hl, keyword_nil, keyword_nil}, 0x23, false},
    {2, {keyword_inc, keyword_h, keyword_nil, keyword_nil}, 0x24, false},
    {2, {keyword_dec, keyword_h, keyword_nil, keyword_nil}, 0x25, false},
    {3, {keyword_ld, keyword_h, keyword_u8, keyword_nil}, 0x26, false},
    {1, {keyword_daa, keyword_nil, keyword_nil, keyword_nil}, 0x27, false},
    {3, {keyword_jr, keyword_flag_z, keyword_r8, keyword_nil}, 0x28, false},
    {3, {keyword_add, keyword_hl, keyword_hl, keyword_nil}, 0x29, false},
    {3, {keyword_ld, keyword_a, keyword_hl, keyword_nil}, 0x2a, false},
    {2, {keyword_dec, keyword_hl, keyword_nil, keyword_nil}, 0x2b, false},
    {2, {keyword_inc, keyword_l, keyword_nil, keyword_nil}, 0x2c, false},
    {2, {keyword_dec, keyword_l, keyword_nil, keyword_nil}, 0x2d, false},
    {3, {keyword_ld, keyword_l, keyword_u8, keyword_nil}, 0x2e, false},
    {1, {keyword_cpl, keyword_nil, keyword_nil, keyword_nil}, 0x2f, false},
    {3, {keyword_jr, keyword_flag_nc, keyword_r8, keyword_nil}, 0x30, false},
    {3, {keyword_ld, keyword_sp, keyword_u16, keyword_nil}, 0x31, false},
    {3, {keyword_ld, keyword_hl, keyword_a, keyword_nil}, 0x32, false},
    {2, {keyword_inc, keyword_sp, keyword_nil, keyword_nil}, 0x33, false},
    {2, {keyword_inc, keyword_hl, keyword_nil, keyword_nil}, 0x34, false},
    {2, {keyword_dec, keyword_hl, keyword_nil, keyword_nil}, 0x35, false},
    {3, {keyword_ld, keyword_hl, keyword_u8, keyword_nil}, 0x36, false},
    {1, {keyword_scf, keyword_nil, keyword_nil, keyword_nil}, 0x37, false},
    {3, {keyword_jr, keyword_flag_cy, keyword_r8, keyword_nil}, 0x38, false},
    {3, {keyword_add, keyword_hl, keyword_sp, keyword_nil}, 0x39, false},
    {3, {keyword_ld, keyword_a, keyword_hl, keyword_nil}, 0x3a, false},
    {2, {keyword_dec, keyword_sp, keyword_nil, keyword_nil}, 0x3b, false},
    {2, {keyword_inc, keyword_a, keyword_nil, keyword_nil}, 0x3c, false},
    {2, {keyword_dec, keyword_a, keyword_nil, keyword_nil}, 0x3d, false},
    {3, {keyword_ld, keyword_a, keyword_u8, keyword_nil}, 0x3e, false},
    {1, {keyword_ccf, keyword_nil, keyword_nil, keyword_nil}, 0x3f, false},
    {3, {keyword_ld, keyword_b, keyword_b, keyword_nil}, 0x40, false},
    {3, {keyword_ld, keyword_b, keyword_c, keyword_nil}, 0x41, false},
    {3, {keyword_ld, keyword_b, keyword_d, keyword_nil}, 0x42, false},
    {3, {keyword_ld, keyword_b, keyword_e, keyword_nil}, 0x43, false},
    {3, {keyword_ld, keyword_b, keyword_h, keyword_nil}, 0x44, false},
    {3, {keyword_ld, keyword_b, keyword_l, keyword_nil}, 0x45, false},
    {3, {keyword_ld, keyword_b, keyword_hl, keyword_nil}, 0x46, false},
    {3, {keyword_ld, keyword_b, keyword_a, keyword_nil}, 0x47, false},
    {3, {keyword_ld, keyword_c, keyword_b, keyword_nil}, 0x48, false},
    {3, {keyword_ld, keyword_c, keyword_c, keyword_nil}, 0x49, false},
    {3, {keyword_ld, keyword_c, keyword_d, keyword_nil}, 0x4a, false},
    {3, {keyword_ld, keyword_c, keyword_e, keyword_nil}, 0x4b, false},
    {3, {keyword_ld, keyword_c, keyword_h, keyword_nil}, 0x4c, false},
    {3, {keyword_ld, keyword_c, keyword_l, keyword_nil}, 0x4d, false},
    {3, {keyword_ld, keyword_c, keyword_hl, keyword_nil}, 0x4e, false},
    {3, {keyword_ld, keyword_c, keyword_a, keyword_nil}, 0x4f, false},
    {3, {keyword_ld, keyword_d, keyword_b, keyword_nil}, 0x50, false},
    {3, {keyword_ld, keyword_d, keyword_c, keyword_nil}, 0x51, false},
    {3, {keyword_ld, keyword_d, keyword_d, keyword_nil}, 0x52, false},
    {3, {keyword_ld, keyword_d, keyword_e, keyword_nil}, 0x53, false},
    {3, {keyword_ld, keyword_d, keyword_h, keyword_nil}, 0x54, false},
    {3, {keyword_ld, keyword_d, keyword_l, keyword_nil}, 0x55, false},
    {3, {keyword_ld, keyword_d, keyword_hl, keyword_nil}, 0x56, false},
    {3, {keyword_ld, keyword_d, keyword_a, keyword_nil}, 0x57, false},
    {3, {keyword_ld, keyword_e, keyword_b, keyword_nil}, 0x58, false},
    {3, {keyword_ld, keyword_e, keyword_c, keyword_nil}, 0x59, false},
    {3, {keyword_ld, keyword_e, keyword_d, keyword_nil}, 0x5a, false},
    {3, {keyword_ld, keyword_e, keyword_e, keyword_nil}, 0x5b, false},
    {3, {keyword_ld, keyword_e, keyword_h, keyword_nil}, 0x5c, false},
    {3, {keyword_ld, keyword_e, keyword_l, keyword_nil}, 0x5d, false},
    {3, {keyword_ld, keyword_e, keyword_hl, keyword_nil}, 0x5e, false},
    {3, {keyword_ld, keyword_e, keyword_a, keyword_nil}, 0x5f, false},
    {3, {keyword_ld, keyword_h, keyword_b, keyword_nil}, 0x60, false},
    {3, {keyword_ld, keyword_h, keyword_c, keyword_nil}, 0x61, false},
    {3, {keyword_ld, keyword_h, keyword_d, keyword_nil}, 0x62, false},
    {3, {keyword_ld, keyword_h, keyword_e, keyword_nil}, 0x63, false},
    {3, {keyword_ld, keyword_h, keyword_h, keyword_nil}, 0x64, false},
    {3, {keyword_ld, keyword_h, keyword_l, keyword_nil}, 0x65, false},
    {3, {keyword_ld, keyword_h, keyword_hl, keyword_nil}, 0x66, false},
    {3, {keyword_ld, keyword_h, keyword_a, keyword_nil}, 0x67, false},
    {3, {keyword_ld, keyword_l, keyword_b, keyword_nil}, 0x68, false},
    {3, {keyword_ld, keyword_l, keyword_c, keyword_nil}, 0x69, false},
    {3, {keyword_ld, keyword_l, keyword_d, keyword_nil}, 0x6a, false},
    {3, {keyword_ld, keyword_l, keyword_e, keyword_nil}, 0x6b, false},
    {3, {keyword_ld, keyword_l, keyword_h, keyword_nil}, 0x6c, false},
    {3, {keyword_ld, keyword_l, keyword_l, keyword_nil}, 0x6d, false},
    {3, {keyword_ld, keyword_l, keyword_hl, keyword_nil}, 0x6e, false},
    {3, {keyword_ld, keyword_l, keyword_a, keyword_nil}, 0x6f, false},
    {3, {keyword_ld, keyword_hl, keyword_b, keyword_nil}, 0x70, false},
    {3, {keyword_ld, keyword_hl, keyword_c, keyword_nil}, 0x71, false},
    {3, {keyword_ld, keyword_hl, keyword_d, keyword_nil}, 0x72, false},
    {3, {keyword_ld, keyword_hl, keyword_e, keyword_nil}, 0x73, false},
    {3, {keyword_ld, keyword_hl, keyword_h, keyword_nil}, 0x74, false},
    {3, {keyword_ld, keyword_hl, keyword_l, keyword_nil}, 0x75, false},
    {1, {keyword_halt, keyword_nil, keyword_nil, keyword_nil}, 0x76, false},
    {3, {keyword_ld, keyword_hl, keyword_a, keyword_nil}, 0x77, false},
    {3, {keyword_ld, keyword_a, keyword_b, keyword_nil}, 0x78, false},
    {3, {keyword_ld, keyword_a, keyword_c, keyword_nil}, 0x79, false},
    {3, {keyword_ld, keyword_a, keyword_d, keyword_nil}, 0x7a, false},
    {3, {keyword_ld, keyword_a, keyword_e, keyword_nil}, 0x7b, false},
    {3, {keyword_ld, keyword_a, keyword_h, keyword_nil}, 0x7c, false},
    {3, {keyword_ld, keyword_a, keyword_l, keyword_nil}, 0x7d, false},
    {3, {keyword_ld, keyword_a, keyword_hl, keyword_nil}, 0x7e, false},
    {3, {keyword_ld, keyword_a, keyword_a, keyword_nil}, 0x7f, false},
    {3, {keyword_add, keyword_a, keyword_b, keyword_nil}, 0x80, false},
    {3, {keyword_add, keyword_a, keyword_c, keyword_nil}, 0x81, false},
    {3, {keyword_add, keyword_a, keyword_d, keyword_nil}, 0x82, false},
    {3, {keyword_add, keyword_a, keyword_e, keyword_nil}, 0x83, false},
    {3, {keyword_add, keyword_a, keyword_h, keyword_nil}, 0x84, false},
    {3, {keyword_add, keyword_a, keyword_l, keyword_nil}, 0x85, false},
    {3, {keyword_add, keyword_a, keyword_hl, keyword_nil}, 0x86, false},
    {3, {keyword_add, keyword_a, keyword_a, keyword_nil}, 0x87, false},
    {3, {keyword_adc, keyword_a, keyword_b, keyword_nil}, 0x88, false},
    {3, {keyword_adc, keyword_a, keyword_c, keyword_nil}, 0x89, false},
    {3, {keyword_adc, keyword_a, keyword_d, keyword_nil}, 0x8a, false},
    {3, {keyword_adc, keyword_a, keyword_e, keyword_nil}, 0x8b, false},
    {3, {keyword_adc, keyword_a, keyword_h, keyword_nil}, 0x8c, false},
    {3, {keyword_adc, keyword_a, keyword_l, keyword_nil}, 0x8d, false},
    {3, {keyword_adc, keyword_a, keyword_hl, keyword_nil}, 0x8e, false},
    {3, {keyword_adc, keyword_a, keyword_a, keyword_nil}, 0x8f, false},
    {2, {keyword_sub, keyword_b, keyword_nil, keyword_nil}, 0x90, false},
    {2, {keyword_sub, keyword_c, keyword_nil, keyword_nil}, 0x91, false},
    {2, {keyword_sub, keyword_d, keyword_nil, keyword_nil}, 0x92, false},
    {2, {keyword_sub, keyword_e, keyword_nil, keyword_nil}, 0x93, false},
    {2, {keyword_sub, keyword_h, keyword_nil, keyword_nil}, 0x94, false},
    {2, {keyword_sub, keyword_l, keyword_nil, keyword_nil}, 0x95, false},
    {2, {keyword_sub, keyword_hl, keyword_nil, keyword_nil}, 0x96, false},
    {2, {keyword_sub, keyword_a, keyword_nil, keyword_nil}, 0x97, false},
    {3, {keyword_sbc, keyword_a, keyword_b, keyword_nil}, 0x98, false},
    {3, {keyword_sbc, keyword_a, keyword_c, keyword_nil}, 0x99, false},
    {3, {keyword_sbc, keyword_a, keyword_d, keyword_nil}, 0x9a, false},
    {3, {keyword_sbc, keyword_a, keyword_e, keyword_nil}, 0x9b, false},
    {3, {keyword_sbc, keyword_a, keyword_h, keyword_nil}, 0x9c, false},
    {3, {keyword_sbc, keyword_a, keyword_l, keyword_nil}, 0x9d, false},
    {3, {keyword_sbc, keyword_a, keyword_hl, keyword_nil}, 0x9e, false},
    {3, {keyword_sbc, keyword_a, keyword_a, keyword_nil}, 0x9f, false},
    {2, {keyword_and, keyword_b, keyword_nil, keyword_nil}, 0xa0, false},
    {2, {keyword_and, keyword_c, keyword_nil, keyword_nil}, 0xa1, false},
    {2, {keyword_and, keyword_d, keyword_nil, keyword_nil}, 0xa2, false},
    {2, {keyword_and, keyword_e, keyword_nil, keyword_nil}, 0xa3, false},
    {2, {keyword_and, keyword_h, keyword_nil, keyword_nil}, 0xa4, false},
    {2, {keyword_and, keyword_l, keyword_nil, keyword_nil}, 0xa5, false},
    {2, {keyword_and, keyword_hl, keyword_nil, keyword_nil}, 0xa6, false},
    {2, {keyword_and, keyword_a, keyword_nil, keyword_nil}, 0xa7, false},
    {2, {keyword_xor, keyword_b, keyword_nil, keyword_nil}, 0xa8, false},
    {2, {keyword_xor, keyword_c, keyword_nil, keyword_nil}, 0xa9, false},
    {2, {keyword_xor, keyword_d, keyword_nil, keyword_nil}, 0xaa, false},
    {2, {keyword_xor, keyword_e, keyword_nil, keyword_nil}, 0xab, false},
    {2, {keyword_xor, keyword_h, keyword_nil, keyword_nil}, 0xac, false},
    {2, {keyword_xor, keyword_l, keyword_nil, keyword_nil}, 0xad, false},
    {2, {keyword_xor, keyword_hl, keyword_nil, keyword_nil}, 0xae, false},
    {2, {keyword_xor, keyword_a, keyword_nil, keyword_nil}, 0xaf, false},
    {2, {keyword_or, keyword_b, keyword_nil, keyword_nil}, 0xb0, false},
    {2, {keyword_or, keyword_c, keyword_nil, keyword_nil}, 0xb1, false},
    {2, {keyword_or, keyword_d, keyword_nil, keyword_nil}, 0xb2, false},
    {2, {keyword_or, keyword_e, keyword_nil, keyword_nil}, 0xb3, false},
    {2, {keyword_or, keyword_h, keyword_nil, keyword_nil}, 0xb4, false},
    {2, {keyword_or, keyword_l, keyword_nil, keyword_nil}, 0xb5, false},
    {2, {keyword_or, keyword_hl, keyword_nil, keyword_nil}, 0xb6, false},
    {2, {keyword_or, keyword_a, keyword_nil, keyword_nil}, 0xb7, false},
    {2, {keyword_cp, keyword_b, keyword_nil, keyword_nil}, 0xb8, false},
    {2, {keyword_cp, keyword_c, keyword_nil, keyword_nil}, 0xb9, false},
    {2, {keyword_cp, keyword_d, keyword_nil, keyword_nil}, 0xba, false},
    {2, {keyword_cp, keyword_e, keyword_nil, keyword_nil}, 0xbb, false},
    {2, {keyword_cp, keyword_h, keyword_nil, keyword_nil}, 0xbc, false},
    {2, {keyword_cp, keyword_l, keyword_nil, keyword_nil}, 0xbd, false},
    {2, {keyword_cp, keyword_hl, keyword_nil, keyword_nil}, 0xbe, false},
    {2, {keyword_cp, keyword_a, keyword_nil, keyword_nil}, 0xbf, false},
    {2, {keyword_ret, keyword_flag_nz, keyword_nil, keyword_nil}, 0xc0, false},
    {2, {keyword_pop, keyword_bc, keyword_nil, keyword_nil}, 0xc1, false},
    {3, {keyword_jp, keyword_flag_nz, keyword_a16, keyword_nil}, 0xc2, false},
    {2, {keyword_jp, keyword_a16, keyword_nil, keyword_nil}, 0xc3, false},
    {3, {keyword_call, keyword_flag_nz, keyword_a16, keyword_nil}, 0xc4, false},
    {2, {keyword_push, keyword_bc, keyword_nil, keyword_nil}, 0xc5, false},
    {3, {keyword_add, keyword_a, keyword_u8, keyword_nil}, 0xc6, false},
    {2, {keyword_rst, keyword_00h, keyword_nil, keyword_nil}, 0xc7, false},
    {2, {keyword_ret, keyword_flag_z, keyword_nil, keyword_nil}, 0xc8, false},
    {1, {keyword_ret, keyword_nil, keyword_nil, keyword_nil}, 0xc9, false},
    {3, {keyword_jp, keyword_flag_z, keyword_a16, keyword_nil}, 0xca, false},
    {1, {keyword_prefix, keyword_nil, keyword_nil, keyword_nil}, 0xcb, false},
    {3, {keyword_call, keyword_flag_z, keyword_a16, keyword_nil}, 0xcc, false},
    {2, {keyword_call, keyword_a16, keyword_nil, keyword_nil}, 0xcd, false},
    {3, {keyword_adc, keyword_a, keyword_u8, keyword_nil}, 0xce, false},
    {2, {keyword_rst, keyword_08h, keyword_nil, keyword_nil}, 0xcf, false},
    {2, {keyword_ret, keyword_flag_nc, keyword_nil, keyword_nil}, 0xd0, false},
    {2, {keyword_pop, keyword_de, keyword_nil, keyword_nil}, 0xd1, false},
    {3, {keyword_jp, keyword_flag_nc, keyword_a16, keyword_nil}, 0xd2, false},
    {1, {keyword_illegal, keyword_nil, keyword_nil, keyword_nil}, 0xd3, false},
    {3, {keyword_call, keyword_flag_nc, keyword_a16, keyword_nil}, 0xd4, false},
    {2, {keyword_push, keyword_de, keyword_nil, keyword_nil}, 0xd5, false},
    {2, {keyword_sub, keyword_u8, keyword_nil, keyword_nil}, 0xd6, false},
    {2, {keyword_rst, keyword_10h, keyword_nil, keyword_nil}, 0xd7, false},
    {2, {keyword_ret, keyword_flag_cy, keyword_nil, keyword_nil}, 0xd8, false},
    {1, {keyword_reti, keyword_nil, keyword_nil, keyword_nil}, 0xd9, false},
    {3, {keyword_jp, keyword_flag_cy, keyword_a16, keyword_nil}, 0xda, false},
    {1, {keyword_illegal, keyword_nil, keyword_nil, keyword_nil}, 0xdb, false},
    {3, {keyword_call, keyword_flag_cy, keyword_a16, keyword_nil}, 0xdc, false},
    {1, {keyword_illegal, keyword_nil, keyword_nil, keyword_nil}, 0xdd, false},
    {3, {keyword_sbc, keyword_a, keyword_u8, keyword_nil}, 0xde, false},
    {2, {keyword_rst, keyword_18h, keyword_nil, keyword_nil}, 0xdf, false},
    {3, {keyword_ldh, keyword_a8, keyword_a, keyword_nil}, 0xe0, false},
    {2, {keyword_pop, keyword_hl, keyword_nil, keyword_nil}, 0xe1, false},
    {3, {keyword_ld, keyword_c, keyword_a, keyword_nil}, 0xe2, false},
    {1, {keyword_illegal, keyword_nil, keyword_nil, keyword_nil}, 0xe3, false},
    {1, {keyword_illegal, keyword_nil, keyword_nil, keyword_nil}, 0xe4, false},
    {2, {keyword_push, keyword_hl, keyword_nil, keyword_nil}, 0xe5, false},
    {2, {keyword_and, keyword_u8, keyword_nil, keyword_nil}, 0xe6, false},
    {2, {keyword_rst, keyword_20h, keyword_nil, keyword_nil}, 0xe7, false},
    {3, {keyword_add, keyword_sp, keyword_r8, keyword_nil}, 0xe8, false},
    {2, {keyword_jp, keyword_hl, keyword_nil, keyword_nil}, 0xe9, false},
    {3, {keyword_ld, keyword_a16, keyword_a, keyword_nil}, 0xea, false},
    {1, {keyword_illegal, keyword_nil, keyword_nil, keyword_nil}, 0xeb, false},
    {1, {keyword_illegal, keyword_nil, keyword_nil, keyword_nil}, 0xec, false},
    {1, {keyword_illegal, keyword_nil, keyword_nil, keyword_nil}, 0xed, false},
    {2, {keyword_xor, keyword_u8, keyword_nil, keyword_nil}, 0xee, false},
    {2, {keyword_rst, keyword_28h, keyword_nil, keyword_nil}, 0xef, false},
    {3, {keyword_ldh, keyword_a, keyword_a8, keyword_nil}, 0xf0, false},
    {2, {keyword_pop, keyword_af, keyword_nil, keyword_nil}, 0xf1, false},
    {3, {keyword_ld, keyword_a, keyword_c, keyword_nil}, 0xf2, false},
    {1, {keyword_di, keyword_nil, keyword_nil, keyword_nil}, 0xf3, false},
    {1, {keyword_illegal, keyword_nil, keyword_nil, keyword_nil}, 0xf4, false},
    {2, {keyword_push, keyword_af, keyword_nil, keyword_nil}, 0xf5, false},
    {2, {keyword_or, keyword_u8, keyword_nil, keyword_nil}, 0xf6, false},
    {2, {keyword_rst, keyword_30h, keyword_nil, keyword_nil}, 0xf7, false},
    {4, {keyword_ld, keyword_hl, keyword_sp, keyword_r8}, 0xf8, false},
    {3, {keyword_ld, keyword_sp, keyword_hl, keyword_nil}, 0xf9, false},
    {3, {keyword_ld, keyword_a, keyword_a16, keyword_nil}, 0xfa, false},
    {1, {keyword_ei, keyword_nil, keyword_nil, keyword_nil}, 0xfb, false},
    {1, {keyword_illegal, keyword_nil, keyword_nil, keyword_nil}, 0xfc, false},
    {1, {keyword_illegal, keyword_nil, keyword_nil, keyword_nil}, 0xfd, false},
    {2, {keyword_cp, keyword_u8, keyword_nil, keyword_nil}, 0xfe, false},
    {2, {keyword_rst, keyword_38h, keyword_nil, keyword_nil}, 0xff, false}
};

